ProjectManagement/Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjectManagement.Models;

namespace ProjectManagement.Controllers
{
    public class DepartmentController : Controller
    {
        private DbModel db = new DbModel();

        public ActionResult Index()
        {
            var pHONGBANs = db.PHONGBANs.Include(p => p.TRUSO_PHONG);
            return View(pHONGBANs.ToList());
        }

        public ActionResult Create()
        {
            ViewBag.MaPB = new SelectList(db.TRUSO_PHONGs, "MaPB", "TruSo");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaPB,TenPB,TrPhong,NgayNhanChuc")] PHONGBAN pHONGBAN)
        {
            if (ModelState.IsValid)
            {
                db.PHONGBANs.Add(pHONGBAN);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaPB = new SelectList(db.TRUSO_PHONGs, "MaPB", "TruSo", pHONGBAN.MaPB);
            return View(pHONGBAN);
        }

        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PHONGBAN pHONGBAN = db.PHONGBANs.Find(id);
            if (pHONGBAN == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaPB = new SelectList(db.TRUSO_PHONGs, "MaPB", "TruSo", pHONGBAN.MaPB);
            return View(pHONGBAN);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaPB,TenPB,TrPhong,NgayNhanChuc,TruSo")] PHONGBAN pHONGBAN)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pHONGBAN).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaPB = new SelectList(db.TRUSO_PHONGs, "MaPB", "TruSo", pHONGBAN.MaPB);
            return View(pHONGBAN);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjectManagement/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjectManagement.Models;

namespace ProjectManagement.Controllers
{
    public class EmployeesController : Controller
    {
        private DbModel db = new DbModel();

        public ActionResult Index()
        {
            var nHANVIENs = db.NHANVIENs.Include(n => n.PHONGBAN);
            return View(nHANVIENs.ToList());
        }

        public ActionResult Create()
        {
            ViewBag.GioiTinh = new SelectList(
                new List<SelectListItem>
                {
                    new SelectListItem { Text = "Nam", Value = "1"},
                    new SelectListItem { Text = "Nữ", Value = "0"},
                }, "Value", "Text"
            );
            ViewBag.MaPB = new SelectList(db.PHONGBANs, "MaPB", "TenPB");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaNV,HoNV,TenNV,NgaySinh,DiaChi,GioiTinh,DienThoai,MaPB")] NHANVIEN nHANVIEN)
        {
            if (ModelState.IsValid)
            {
                db.NHANVIENs.Add(nHANVIEN);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.GioiTinh = new SelectList(
                new List<SelectListItem>
                {
                    new SelectListItem { Text = "Nam", Value = "1"},
                    new SelectListItem { Text = "Nữ", Value = "0"},
                }, "Value", "Text", nHANVIEN.GioiTinh
            );
            ViewBag.MaPB = new SelectList(db.PHONGBANs, "MaPB", "TenPB", nHANVIEN.MaPB);
            return View(nHANVIEN);
        }

        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NHANVIEN nHANVIEN = db.NHANVIENs.Find(id);
            if (nHANVIEN == null)
            {
                return HttpNotFound();
            }
            ViewBag.GioiTinh = new SelectList(
                new List<SelectListItem>
                {
                    new SelectListItem { Text = "Nam", Value = "1"},
                    new SelectListItem { Text = "Nữ", Value = "0"},

                }, "Value", "Text", nHANVIEN.GioiTinh
            );
            ViewBag.MaPB = new SelectList(db.PHONGBANs, "MaPB", "TenPB", nHANVIEN.MaPB);
            return View(nHANVIEN);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaNV,HoNV,TenNV,NgaySinh,DiaChi,GioiTinh,DienThoai,MaPB")] NHANVIEN nHANVIEN)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nHANVIEN).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.GioiTinh = new SelectList(
                new List<SelectListItem>
                {
                    new SelectListItem { Text = "Nam", Value = "1"},
                    new SelectListItem { Text = "Nữ", Value = "0"},
                }, "Value", "Text", nHANVIEN.GioiTinh
            );
            ViewBag.MaPB = new SelectList(db.PHONGBANs, "MaPB", "TenPB", nHANVIEN.MaPB);
            return View(nHANVIEN);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjectManagement/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjectManagement.Models;

namespace ProjectManagement.Controllers
{
    public class ProjectController : Controller
    {
        private DbModel db = new DbModel();

        public ActionResult Index()
        {
            var dUANs = db.DUANs.Include(d => d.PHONGBAN);
            return View(dUANs.ToList());
        }

        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DUAN dUAN = db.DUANs.Find(id);
            if (dUAN == null)
            {
                return HttpNotFound();
            }
            return View(dUAN);
        }

        public ActionResult Create()
        {
            ViewBag.MaPB = new SelectList(db.PHONGBANs, "MaPB", "TenPB");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaDA,TenDA,DiaDiem,MaPB")] DUAN dUAN)
        {
            if (ModelState.IsValid)
            {
                db.DUANs.Add(dUAN);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaPB = new SelectList(db.PHONGBANs, "MaPB", "TenPB", dUAN.MaPB);
            return View(dUAN);
        }

        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DUAN dUAN = db.DUANs.Find(id);
            if (dUAN == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaPB = new SelectList(db.PHONGBANs, "MaPB", "TenPB", dUAN.MaPB);
            return View(dUAN);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaDA,TenDA,DiaDiem,MaPB")] DUAN dUAN)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dUAN).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaPB = new SelectList(db.PHONGBANs, "MaPB", "TenPB", dUAN.MaPB);
            return View(dUAN);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjectManagement/Controllers/ProjectEmployeesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjectManagement.Models;

namespace ProjectManagement.Controllers
{
    public class ProjectEmployeesController : Controller
    {
        private DbModel db = new DbModel();

        public ActionResult Index()
        {
            var tHAMGIAs = db.THAMGIAs.Include(t => t.DUAN).Include(t => t.NHANVIEN);
            return View(tHAMGIAs.ToList());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            THAMGIA tHAMGIA = db.THAMGIAs.Find(id);
            if (tHAMGIA == null)
            {
                return HttpNotFound();
            }
            return View(tHAMGIA);
        }

        public ActionResult Create()
        {
            ViewBag.MaDA = new SelectList(db.DUANs, "MaDA", "TenDA");
            ViewBag.MaNV = new SelectList(db.NHANVIENs, "MaNV", "TenNV");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,MaNV,MaDA,SoGio")] THAMGIA tHAMGIA)
        {
            if (ModelState.IsValid)
            {
                db.THAMGIAs.Add(tHAMGIA);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaDA = new SelectList(db.DUANs, "MaDA", "TenDA", tHAMGIA.MaDA);
            ViewBag.MaNV = new SelectList(db.NHANVIENs, "MaNV", "TenNV", tHAMGIA.MaNV);
            return View(tHAMGIA);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            THAMGIA tHAMGIA = db.THAMGIAs.Find(id);
            if (tHAMGIA == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaDA = new SelectList(db.DUANs, "MaDA", "TenDA", tHAMGIA.MaDA);
            ViewBag.MaNV = new SelectList(db.NHANVIENs, "MaNV", "TenNV", tHAMGIA.MaNV);
            return View(tHAMGIA);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,MaNV,MaDA,SoGio")] THAMGIA tHAMGIA)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tHAMGIA).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaDA = new SelectList(db.DUANs, "MaDA", "TenDA", tHAMGIA.MaDA);
            ViewBag.MaNV = new SelectList(db.NHANVIENs, "MaNV", "TenNV", tHAMGIA.MaNV);
            return View(tHAMGIA);
        }
        
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjectManagement/Views/Shared/_Footer.cshtml
<div class="row">
    <div class="col-md-12">
        <div class="copyright">
            <p>Copyright © 2018 Colorlib. All rights reserved. Template by <a href="https://colorlib.com">Colorlib</a>.</p>
        </div>
    </div>
</div>

ProjectManagement/Views/Shared/_Header.cshtml
<header class="header-desktop">
    <div class="section__content section__content--p30">
        <div class="container-fluid">
            <div class="header-wrap">
                <form class="form-header" action="" method="POST">
                    <input class="au-input au-input--xl" type="text" name="search" placeholder="Tìm kiếm..." />
                    <button class="au-btn--submit" type="submit">
                        <i class="zmdi zmdi-search"></i>
                    </button>
                </form>
                <div class="header-button">
                    <div class="noti-wrap">
                        <div class="noti__item js-item-menu">
                            <i class="zmdi zmdi-comment-more"></i>
                            <span class="quantity">1</span>
                        </div>
                        <div class="noti__item js-item-menu">
                            <i class="zmdi zmdi-email"></i>
                            <span class="quantity">1</span>
                        </div>
                        <div class="noti__item js-item-menu">
                            <i class="zmdi zmdi-notifications"></i>
                            <span class="quantity">3</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

ProjectManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewBag.Title</title>
    <link href="~/Content/css/font-face.css" rel="stylesheet" media="all">
    <link href="~/Content/vendor/font-awesome-4.7/css/font-awesome.min.css" rel="stylesheet" media="all">
    <link href="~/Content/vendor/font-awesome-5/css/fontawesome-all.min.css" rel="stylesheet" media="all">
    <link href="~/Content/vendor/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" media="all">
    <!-- Bootstrap CSS-->
    <link href="~/Content/vendor/bootstrap-4.1/bootstrap.min.css" rel="stylesheet" media="all">
    <!-- Vendor CSS-->
    <link href="~/Content/vendor/animsition/animsition.min.css" rel="stylesheet" media="all">
    <link href="~/Content/vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet" media="all">
    <link href="~/Content/vendor/wow/animate.css" rel="stylesheet" media="all">
    <link href="~/Content/vendor/css-hamburgers/hamburgers.min.css" rel="stylesheet" media="all">
    <link href="~/Content/vendor/slick/slick.css" rel="stylesheet" media="all">
    <link href="~/Content/vendor/select2/select2.min.css" rel="stylesheet" media="all">
    <link href="~/Content/vendor/perfect-scrollbar/perfect-scrollbar.css" rel="stylesheet" media="all">

    <link href="https://cdn.datatables.net/v/bs4/dt-1.10.16/datatables.min.css" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="~/Content/css/theme.css" rel="stylesheet" media="all">

    <script src="~/Content/vendor/jquery-3.2.1.min.js"></script>
</head>
<body class="animsition">
    <div class="page-wrapper">
        <!-- MENU SIDEBAR-->
        @{Html.RenderPartial("_Sidebar");}
        <!-- END MENU SIDEBAR-->
        <!-- PAGE CONTAINER-->
        <div class="page-container">
            <!-- HEADER-->
            @{Html.RenderPartial("_Header");}
            <!-- HEADER-->
            <!-- MAIN CONTENT-->
            <div class="main-content">
                <div class="section__content section__content--p30">
                    <div class="container-fluid">
                        @RenderBody()
                        @*@{Html.RenderPartial("_Footer");}*@
                    </div>
                </div>
            </div>
            <!-- END MAIN CONTENT-->
            <!-- END PAGE CONTAINER-->
        </div>
    </div>
    <!-- Jquery JS-->
    <!-- Bootstrap JS-->
    <script src="~/Content/vendor/bootstrap-4.1/popper.min.js"></script>
    <script src="~/Content/vendor/bootstrap-4.1/bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/v/bs4/dt-1.10.16/datatables.min.js"></script>
    <!-- Vendor JS       -->
    <script src="~/Content/vendor/slick/slick.min.js">
    </script>
    <script src="~/Content/vendor/wow/wow.min.js"></script>
    <script src="~/Content/vendor/animsition/animsition.min.js"></script>
    <script src="~/Content/vendor/bootstrap-progressbar/bootstrap-progressbar.min.js">
    </script>
    <script src="~/Content/vendor/counter-up/jquery.waypoints.min.js"></script>
    <script src="~/Content/vendor/counter-up/jquery.counterup.min.js">
    </script>
    <script src="~/Content/vendor/circle-progress/circle-progress.min.js"></script>
    <script src="~/Content/vendor/perfect-scrollbar/perfect-scrollbar.js"></script>
    <script src="~/Content/vendor/chartjs/Chart.bundle.min.js"></script>
    <script src="~/Content/vendor/select2/select2.min.js">
    </script>
    <!-- Main JS-->
    <script src="~/Content/js/main.js"></script>
</body>

</html>

ProjectManagement/Views/Shared/_Sidebar.cshtml
<aside class="menu-sidebar d-none d-lg-block">
    <div class="logo">
        <a href="#">
            <img src="~/Content/images/icon/logo.png" alt="Công Ty TNHH Tập Đoàn Xây Dựng DELTA" />
        </a>
    </div>
    <div class="menu-sidebar__content js-scrollbar1">
        <nav class="navbar-sidebar">
            <ul class="list-unstyled navbar__list">
                <li class="active">
                    <a class="js-arrow" href="@Url.Action("Index","Home")">
                        <i class="fas fa-tachometer-alt"></i>Thống kê
                    </a>
                </li>
                <li>
                    <a class="js-arrow" href="@Url.Action("Index","Department")">
                        <i class="fas fa-university"></i>Phòng ban
                    </a>
                </li>
                <li>
                    <a class="js-arrow" href="@Url.Action("Index","Employees")">
                        <i class="fas fa-users"></i>Nhân viên
                    </a>
                </li>
                <li class="has-sub">
                    <a class="js-arrow" href="#">
                        <i class="fas fa-suitcase"></i>Dự án
                    </a>
                    <ul class="list-unstyled navbar__sub-list js-sub-list">
                        <li>
                            <a href="@Url.Action("Index","Project")">Dự án</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index","ProjectEmployees")">Nhân viên</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
    </div>
</aside>